MPQC: sc::RedundantCartesianSubIterV3 Class Reference
sc::RedundantCartesianSubIterV3 Class Reference
Public Member Functions
RedundantCartesianSubIterV3 (int l)
void start (int aa, int bb, int cc)
Initialize the iterator.
int bfn () const
Return the current Cartesian basis function number.
Public Member Functions inherited from sc::RedundantCartesianSubIter
RedundantCartesianSubIter (int l)
Create a object for the given angular momentum.
void next ()
Move to the next combination of axes.
operator int () const
Returns nonzero if the iterator currently hold valid data.
int a () const
The current exponent of x.
int b () const
The current exponent of y.
int c () const
The current exponent of z.
int l () const
The angular momentum.
int l (int i)
Returns a() if i==0, b() if i==1, and c() if i==2.
int axis (int i)
Return the i'th axis.
Member Function Documentation
bfn()
int sc::RedundantCartesianSubIterV3::bfn () const inline virtual
Return the current Cartesian basis function number.
Since Cartesian basis function index is constant on the iteration range of this object, this is a const function.
See also
RedundantCartesianIter for more information
Implements sc::RedundantCartesianSubIter.
start()
void sc::RedundantCartesianSubIterV3::start (int a, int b, int c) inline virtual
Initialize the iterator.
The constraints on a, b, and c are given as arguments.
Reimplemented from sc::RedundantCartesianSubIter.
References sc::RedundantCartesianSubIter::a(), sc::RedundantCartesianSubIter::b(), sc::RedundantCartesianSubIter::l(), and sc::RedundantCartesianSubIter::start().
The documentation for this class was generated from the following file:
src/lib/chemistry/qc/intv3/cartitv3.h
Generated at Sun Jan 26 2020 23:24:10 for MPQC 3.0.0-alpha using the documentation package Doxygen 1.8.16.