MPQC: sc::DescribedClass Class Reference
sc::DescribedClass Class Reference
Classes which need runtime information about themselves and their relationship to other classes can virtually inherit from DescribedClass.
#include <util/class/class.h>
Public Member Functions
DescribedClass (const DescribedClass &)
DescribedClass & operator= (const DescribedClass &)
ClassDesc * class_desc () const MPQC__NOEXCEPT
This returns the unique pointer to the ClassDesc corresponding to the given type_info object.
const char * class_name () const
Return the name of the object's exact type.
int class_version () const
Return the version of the class.
virtual void print (std::ostream &=ExEnv::out0()) const
Print the object.
Ref< DescribedClass > ref ()
Return this object wrapped up in a Ref smart pointer.
Public Member Functions inherited from sc::RefCount
size_t identifier () const
Return the unique identifier for this object that can be compared for different objects of different types.
int lock_ptr () const
Lock this object.
int unlock_ptr () const
Unlock this object.
void use_locks (bool inVal)
start and stop using locks on this object
refcount_t nreference () const
Return the reference count.
refcount_t reference ()
Increment the reference count and return the new count.
refcount_t dereference ()
Decrement the reference count and return the new count.
int managed () const
void unmanage ()
Turn off the reference counting mechanism for this object.
Additional Inherited Members
Protected Member Functions inherited from sc::RefCount
RefCount (const RefCount &)
RefCount & operator= (const RefCount &)
Detailed Description
Classes which need runtime information about themselves and their relationship to other classes can virtually inherit from DescribedClass.
This will provide the class with the ability to query its name and its version. Furthermore, the class's static ClassDesc can be obtained which permits several other operations. See The Described Class Library for more information.
Member Function Documentation
class_desc()
ClassDesc* sc::DescribedClass::class_desc () const
This returns the unique pointer to the ClassDesc corresponding to the given type_info object.
Null is returned if it fails.
Referenced by sc::ConsumableResources::manage_array(), sc::require_dynamic_cast(), and sc::ConsumableResources::unmanage_array().
ref()
Ref<DescribedClass> sc::DescribedClass::ref () inline
Return this object wrapped up in a Ref smart pointer.
This member is mainly a convenience function for the Python MPQC interface.
The documentation for this class was generated from the following file:
src/lib/util/class/class.h
Generated at Sun Jan 26 2020 23:24:04 for MPQC 3.0.0-alpha using the documentation package Doxygen 1.8.16.