MPQC: sc::SphericalTransformComponentLibint2 Class Reference
sc::SphericalTransformComponentLibint2 Class Reference
Public Member Functions
void init (int a, int b, int c, double coef, int pureindex)
Initialize this object.
Public Member Functions inherited from sc::SphericalTransformComponent
int a () const
Returns the exponent of x.
int b () const
Returns the exponent of y.
int c () const
Returns the exponent of z.
int cartindex () const
Returns the index of the Cartesian basis function.
int pureindex () const
Returns the index solid harmonic basis function.
double coef () const
Returns the coefficient of this component of the transformation.
Additional Inherited Members
Protected Attributes inherited from sc::SphericalTransformComponent
double coef_
int a_
int b_
int c_
int cartindex_
int pureindex_
Member Function Documentation
init()
void sc::SphericalTransformComponentLibint2::init (int a, int b, int c, double coef, int pureindex) inline virtual
Initialize this object.
This must be provided in all specializations of this class to establish the ordering between a, b and c and the index of the Cartesian basis function. Other things such as adjustment of the coefficient to account for normalization differences can be done as well. The default SphericalTransform::init() implementation requires that only the xl, yl and zl basis functions are normalized to unity.
Implements sc::SphericalTransformComponent.
References sc::SphericalTransformComponent::a(), sc::SphericalTransformComponent::b(), sc::SphericalTransformComponent::c(), sc::SphericalTransformComponent::coef(), and sc::SphericalTransformComponent::pureindex().
The documentation for this class was generated from the following file:
src/lib/chemistry/qc/libint2/tform.h
Generated at Sun Jan 26 2020 23:24:12 for MPQC 3.0.0-alpha using the documentation package Doxygen 1.8.16.