MPQC: mpqc.Chemistry.Basis.Gaussian
mpqc.Chemistry.Basis.Gaussian
mpqc.Chemistry » mpqc.Chemistry.Basis
Classes
class sc::GaussianBasisSet
The GaussianBasisSet class is used describe a basis set composed of atomic gaussian orbitals.
class sc::GaussianBasisSetMap
A heavy-duty map from one GaussianBasisSet to another GaussianBasisSet.
class sc::WriteBasisGrid
class sc::GaussianShell
A shell of Gaussian functions.
Functions
Ref< GaussianBasisSet > sc::operator+ (const Ref< GaussianBasisSet > &A, const Ref< GaussianBasisSet > &B)
Nonmember operator+ is more convenient to use than the member operator+.
int sc::ishell_on_center (int icenter, const Ref< GaussianBasisSet > &bs, const GaussianShell &A)
Find A in bs on center icenter and return its index.
std::vector< unsigned int > sc::operator<< (const GaussianBasisSet &B, const GaussianBasisSet &A)
computes a map from basis functions in A to the equivalent basis functions in B.
std::vector< int > sc::map (const GaussianBasisSet &B, const GaussianBasisSet &A)
same as operator<<, except A does not have to be contained in B, map[a] = -1 if function a is not in B
template<typename Filter >
GaussianShell sc::filter (const GaussianShell &shell, Filter f)
constructs a new GaussianShell from shell by applying Filter filter
void sc::ToStateOut (const GaussianShell &s, StateOut &so, int &count)
writes GaussianShell to sc::StateOut
void sc::FromStateIn (GaussianShell &s, StateIn &si, int &count)
reads GaussianShell from sc::StateIn
Detailed Description
Classes/functions related to Gaussian AO basis representations.
Function Documentation
filter()
template<typename Filter > GaussianShell sc::filter (const GaussianShell & shell, Filter f)
constructs a new GaussianShell from shell by applying Filter filter
Template Parameters
Filter boolear functor that returns true if contraction is to be kept, must provide bool Filter(const GaussianShell& shell, unsigned int contr)
Parameters
shell
f Filter object
Returns
References sc::GaussianShell::am(), sc::GaussianShell::coefficient_unnorm_block(), sc::GaussianShell::exponents(), sc::GaussianShell::is_pure(), sc::GaussianShell::ncontraction(), and sc::GaussianShell::nprimitive().
operator<<()
std::vector<unsigned int> sc::operator<< (const GaussianBasisSet & B, const GaussianBasisSet & A)
computes a map from basis functions in A to the equivalent basis functions in B.
A must be contained in B, else will throw
Generated at Sun Jan 26 2020 23:24:02 for MPQC 3.0.0-alpha using the documentation package Doxygen 1.8.16.