MPQC: mpqc.Core.File
mpqc.Core.File
mpqc.Core
Namespaces
mpqc::detail::File
implementation details
Classes
struct mpqc::File::Dataspace< T_ >
A subset of File::Dataset.
struct mpqc::File::Dataset< T >
Array-like collection of data.
struct mpqc::File::Group
Directory-like container that holds datasets and other groups.
struct mpqc::File
Top-level file object that holds groups.
Functions
template<typename T , class A >
void mpqc::operator>> (File::Dataset< T > ds, A &a)
Read from dataset into a generic container A.
template<typename T , class A >
void mpqc::operator<< (File::Dataset< T > ds, const A &a)
Write to dataset from a generic container A.
template<typename T , class A >
void mpqc::operator>> (File::Dataspace< T > ds, A &a)
Read from dataspace into a generic container A.
template<typename T , class A >
void mpqc::operator<< (File::Dataspace< T > ds, const A &a)
Write to dataspace from a generic container A.
Group mpqc::File::group (const std::string &name="/")
Creates or opens a file group.
Detailed Description
Implementation of hierarchical file objects based on HDF5.
To work with files:
create a file object
create a dataset in that file (where actual data resides)
write/read data to/from the dataset
File file("file.h5");
std::vector<size_t> dims{m,n};
File::Dataset<double> ds(file, "my dataset", dims);
Vector v(m*n);
ds.write(v.data());
ds.read(v.data());
// or
ds << v; // write v to ds
ds >> v; // read ds to v
Function Documentation
group()
File::Group mpqc::File::group (const std::string & name = "/") inline
Creates or opens a file group.
Parameters
[in] name group name. Default argument implies default group.
Warning
NOT threadsafe
References mpqc::File::Group::create().
operator<<() [1/2]
template<typename T , class A > void mpqc::operator<< (File::Dataset< T > ds, const A & a)
Write to dataset from a generic container A.
Template Parameters
A Container with member const T* A::data()
Parameters
ds Dataset to write to
a Container to read from.
Warning
The pointer returned by A::data() must be contigous
References mpqc::File::Dataset< T >::write().
operator<<() [2/2]
template<typename T , class A > void mpqc::operator<< (File::Dataspace< T > ds, const A & a)
Write to dataspace from a generic container A.
Template Parameters
A Container with member const T* A::data()
Parameters
ds Dataspace to write to
a Container to read from.
Warning
The pointer returned by A::data() must be contigous
operator>>() [1/2]
template<typename T , class A > void mpqc::operator>> (File::Dataset< T > ds, A & a)
Read from dataset into a generic container A.
Template Parameters
A Container with member T* A::data()
Parameters
ds Dataset to read from
a Container to read to.
Warning
The pointer returned by A::data() must be contigous
References mpqc::File::Dataset< T >::read().
operator>>() [2/2]
template<typename T , class A > void mpqc::operator>> (File::Dataspace< T > ds, A & a)
Read from dataspace into a generic container A.
Template Parameters
A Container with member T* A::data()
Parameters
ds Dataspace to read from
a Container to read to.
Warning
The pointer returned by A::data() must be contigous
Generated at Sun Jan 26 2020 23:24:02 for MPQC 3.0.0-alpha using the documentation package Doxygen 1.8.16.