MPQC: mpqc::ci::Vector Struct Reference
mpqc::ci::Vector Struct Reference
mpqc.Chemistry » mpqc.Chemistry.ElectronicStructure » mpqc.Chemistry.ElectronicStructure.NBody » mpqc.Chemistry.ElectronicStructure.NBody.CI
Block CI Vector, with 1-d (vector) and 2-d (matrix) access.
#include <mpqc/ci/vector.hpp>
Classes
struct Block1d
1-d vector sub-block
struct Block2d
2-d vector sub-block
Public Member Functions
Vector (std::string name, const SubspaceGrid &G, MPI::Comm comm, bool incore)
Construct vector.
Block1d operator() (range r)
Returns 1-d sub-block of vector.
Block2d operator() (mpqc::range A, mpqc::range B)
Returns 2-d sub-block of vector.
void sync ()
Detailed Description
Block CI Vector, with 1-d (vector) and 2-d (matrix) access.
Constructor & Destructor Documentation
Vector()
mpqc::ci::Vector::Vector (std::string name, const SubspaceGrid & G, MPI::Comm comm, bool incore) inline
Construct vector.
Parameters
name vector name
G vector grid (blocking and sparsity)
comm MPI communicator
incore store vector in core (incore=true) or in file
References mpqc::ci::SubspaceGrid::allowed(), mpqc::ci::SubspaceGrid::alpha(), mpqc::ci::SubspaceGrid::beta(), and mpqc::ci::SubspaceGrid::dets().
Member Function Documentation
operator()()
Block1d mpqc::ci::Vector::operator() (range r) inline
Returns 1-d sub-block of vector.
Parameters
r sub-block range
The documentation for this struct was generated from the following file:
src/lib/mpqc/ci/vector.hpp
Generated at Sun Jan 26 2020 23:24:02 for MPQC 3.0.0-alpha using the documentation package Doxygen 1.8.16.